/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as IndexRouteImport } from './../pages/index'
import { Route as SocialIndexRouteImport } from './../pages/social/index'
import { Route as ProcessosIndexRouteImport } from './../pages/processos/index'
import { Route as PerfilIndexRouteImport } from './../pages/perfil/index'
import { Route as ConfiguracoesIndexRouteImport } from './../pages/configuracoes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/social/',
  path: '/social/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosIndexRoute = ProcessosIndexRouteImport.update({
  id: '/processos/',
  path: '/processos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/processos/': typeof ProcessosIndexRoute
  '/social/': typeof SocialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/processos': typeof ProcessosIndexRoute
  '/social': typeof SocialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/processos/': typeof ProcessosIndexRoute
  '/social/': typeof SocialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configuracoes/' | '/perfil/' | '/processos/' | '/social/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracoes' | '/perfil' | '/processos' | '/social'
  id:
    | '__root__'
    | '/'
    | '/configuracoes/'
    | '/perfil/'
    | '/processos/'
    | '/social/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  ProcessosIndexRoute: typeof ProcessosIndexRoute
  SocialIndexRoute: typeof SocialIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/social'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/': {
      id: '/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof ProcessosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  ProcessosIndexRoute: ProcessosIndexRoute,
  SocialIndexRoute: SocialIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
